version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: accountnt-dev
    volumes:
      - accountnt-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  test-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: accountnt-test
    ports:
      - "5433:5432"

volumes:
  accountnt-dev:
